name: Dependabot automerge
on: pull_request
jobs:
  my-dependabot-job:
    if: ${{ github.event.pull_request.user.login == 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    #if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Dependabot metadata
        id: my-dependabot-metadata
        uses: dependabot/fetch-metadata@v1.3.3
        # Why with?
        #with:
          #github-token: '${{ secrets.GITHUB_TOKEN }}'
      - name: Enable automerge for Dependabot pull requests
        if: >
          ${{
            contains(
              steps.my-dependabot-metadata.outputs.dependency-names,
              'y'
            )
          }}
        #if: ${{ ... && steps.my-dependabot-metadata.outputs.update-type == 'version-update:semver-patch' }}
        run: gh pr merge --auto --merge $PR_URL
        env:
          #GITHUB_TOKEN: ${{ secrets.MY_PUBLIC_REPO_PAT }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
